// This file is automatically generated.
// Please do not change this file!
export const active: string;
export const container: string;
export const file: string;
export const item: string;
export const mappings: string;
export const names: string;
export const reviews: string;
export const sources: string;
export const sourcesContent: string;
export const tabs: string;
export const version: string;
