// This file is automatically generated.
// Please do not change this file!
export const closebtn: string;
export const file: string;
export const main: string;
export const mappings: string;
export const names: string;
export const sidenav: string;
export const sources: string;
export const sourcesContent: string;
export const version: string;
