// This file is automatically generated.
// Please do not change this file!
export const active: string;
export const file: string;
export const header: string;
export const link: string;
export const logo: string;
export const logoSpin: string;
export const mappings: string;
export const names: string;
export const search: string;
export const sources: string;
export const sourcesContent: string;
export const title: string;
export const version: string;
